apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-frontend
  labels:
    app: podtato-head-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podtato-head-frontend
  template:
    metadata:
      labels:
        app: podtato-head-frontend
        role: frontend
    spec:
      volumes:
        - name: services-config
          configMap:
            name: services-config
            items:
            - key: servicesConfig.yaml
              path: servicesConfig.yaml
      containers:
      - name: podtato-head-frontend
        image: ghcr.io/podtato-head/podtato-server:v0.3.1
        ports:
        - containerPort: 8080
        env:
        - name: PODTATO_COMPONENT
          value: "frontend"
        - name: SERVICES_CONFIG_FILE_PATH
          value: "/config/servicesConfig.yaml"
        volumeMounts:
          - mountPath: "/config/servicesConfig.yaml"
            name: services-config
            subPath: servicesConfig.yaml
            readOnly: true
