apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: podtato-head-backend
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: frontend
